language: php

sudo: false

php:
  - 7.3

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install

script:
  - ./vendor/sensiolabs/security-checker/security-checker security:check composer.lock
