version: '3.7'
services:
    php:
        build: ./.docker/php
        working_dir: /app
        volumes:
            - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/app

    composer:
        image: composer
        volumes:
            - ./:/app
