name: Resume

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - run: |
          npm install
      
      - run: |
          npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: resume.pdf
          path: resume.pdf

      - run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.pdf
          git add resume-preview.pdf.png
          git add resume-preview.json.png
          git commit --amend --no-edit

      - uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          force_with_lease: true

      - uses: actions/github-script@v6
        if: github.ref == 'refs/heads/main'
        with:
          script: |       
            const padding = (v) => v < 10 ? `0${v}` : v;

            const date = new Date();
            const year = padding(date.getFullYear());
            const month = padding(date.getMonth());
            const day = padding(date.getDate());
            const hours = padding(date.getHours());
            const minutes = padding(date.getMinutes());
            const seconds = padding(date.getSeconds());

            const major = year - 2023;
            const minor = month;
            const patch = `${day}${hours}${minutes}${seconds}`;

            const releaseName = `${major}.${minor}.${patch}`;

            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${releaseName}`,
                sha: context.sha
            })

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            resume.pdf
